### PR TITLE
Remove mention of no-extension branch in readme.

### PR DESCRIPTION
**Pull request by juanlang**
One more step toward closing #49. @iuliaion, could you please have a look?

### CODE REVIEW

**Comment by leshi** [comment]
Can you add mention of how to make the code use the unbundled extension vs the bundled extension?

**Comment by juanlang** [comment]
@leshi, this is already described in u2f-gae-demo's README.md. I felt it would be redundant here.

**Comment by juanlang** [comment]
@leshi, friendly ping.

**Comment by juanlang** [comment]
@leshi, friendly ping.

**Comment by leshi** [comment]
ack

**Comment by leshi** [comment]
ltm

**Pull request merged**
