### PR TITLE
Use U2F-format requests with Google Authenticator.

### LINKED ISSUE #64: Should use u2f sign requests with Google Authenticator on Android
The reference server is using an documented legacy format for sending requests to Google Authenticator on Android. Instead, it should be using requests of the format:
S.request=<url encoded value of U2fSignRequest>

A hint what a U2fSignRequest looks like, in the format of the 1.1 version of the JavaScript API:
{
  type: "u2f_sign_request",
  challenge: <url-safe base64-encoded challenge bytes>,
  registeredKeys: [{keyHandle: <url-safe encoded key handle bytes>, version: "U2F_V2"}, ...]
}

The U2fSignRequest in the format of the 1.0 version of the JavaScript API is also supported, e.g.:
{
  type: "u2f_sign_request",
  signRequests: [{keyHandle: <url-safe encoded key handle bytes>, version: "U2F_V2", challenge: <url-safe base64-encoded challenge bytes>}, ...]
}

### PR DESCRIPTION
**Pull request by juanlang**
Closes #64.

### CODE REVIEW

**Comment by juanlang** [comment]
@iuliaion, mind having a look?

**Comment by iuliaion** [comment]
I will look into it.

**Comment by juanlang** [comment]
@leshi, maybe you could take a look in Iulia's absence? It mostly just deletes code.

**Comment by leshi** [comment]
lgtm

**Pull request merged**
