### PR TITLE
Output transports in accordance with the U2F spec.

### LINKED ISSUE #120: Demo server outputs transports in non-spec-compliant way
The FIDO U2F JavaScript API version 1.1 adds an optional per-key handle transports value:
https://fidoalliance.org/specs/fido-u2f-v1.0-nfc-bt-amendment-20150514/fido-u2f-javascript-api.html#u2f-transports

This is defined as:
typedef sequence<Transport> Transports;

The web server outputs this value as a comma-delimited string:
https://github.com/google/u2f-ref-code/blob/master/u2f-ref-code/java/src/com/google/u2f/server/messages/RegisteredKey.java#L110

The proper way to represent a WebIDL sequence in JavaScript is as an array:
https://www.w3.org/TR/WebIDL/#es-sequence

As a result, this format confuses clients that expect only spec-compliant transports values.

### PR DESCRIPTION
**Pull request by juanlang**
Fixes #120.

### CODE REVIEW

**Comment by juanlang** [comment]
@leshi, I tested this manually via whitebox testing: I modified the server to return a non-empty list of transports for all U2F devices, and verified that it sends them to Chrome as an array rather than a string.

**Comment by juanlang** [comment]
I signed it!

**Comment by juanlang** [comment]
@leshi, friendly ping.

**Comment by leshi** [comment]
LGTM

**Pull request merged**
